// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Yh35hRj0L8sVxljlPB7emnLMnecrtb0',
    appId: '1:833704703232:web:ddde5564ad8a8feadfefe5',
    messagingSenderId: '833704703232',
    projectId: 'duck1-f7176',
    authDomain: 'duck1-f7176.firebaseapp.com',
    databaseURL: 'https://duck1-f7176-default-rtdb.firebaseio.com',
    storageBucket: 'duck1-f7176.appspot.com',
    measurementId: 'G-SHH5N5HX0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwppuuNPeQv7ZIZhYtP_lFlXeKwMnRhH4',
    appId: '1:833704703232:android:34d0d11b350dbf42dfefe5',
    messagingSenderId: '833704703232',
    projectId: 'duck1-f7176',
    databaseURL: 'https://duck1-f7176-default-rtdb.firebaseio.com',
    storageBucket: 'duck1-f7176.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Yh35hRj0L8sVxljlPB7emnLMnecrtb0',
    appId: '1:833704703232:web:f43523a51b14b213dfefe5',
    messagingSenderId: '833704703232',
    projectId: 'duck1-f7176',
    authDomain: 'duck1-f7176.firebaseapp.com',
    databaseURL: 'https://duck1-f7176-default-rtdb.firebaseio.com',
    storageBucket: 'duck1-f7176.appspot.com',
    measurementId: 'G-K911G6VHKY',
  );

}